# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Generate a file that contains the version number of the package.

The generated file will be used to invalidate XKB cache files in /var/lib/xkb/.
See http://crosbug.com/6261 for details.
"""

__author__ = "yusukes"

import optparse
import re

def main():
  parser = optparse.OptionParser(usage='Usage: %prog [options]')
  parser.add_option('--version', dest='version', default=None,
                    help='Specify the package version of xkeyboard-config')
  parser.add_option('--format', dest='format', default=None,
                    help='Specify the output format ("cpp" or "xkb")')
  (options, _) = parser.parse_args()
  # Hyphens and dots are not allowed in XKB symbol definitions.
  version = 'v' + re.sub(r'[-.]', '_', options.version)
  if (options.format == 'xkb'):
    print """// The file is generated by
// chromiumos-overlay/x11-misc/xkeyboard-config/files/gen_version_files.py
partial modifier_keys
xkb_symbols "%s" {
};""" % version
    return
  else:
    print """// Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// The file is generated by
// chromiumos-overlay/x11-misc/xkeyboard-config/files/gen_version_files.py

#ifndef USR_INCLUDE_XKEYBOARD_CONFIG_VERSION_H_
#define USR_INCLUDE_XKEYBOARD_CONFIG_VERSION_H_
namespace chromeos {
const char kXkeyboardConfigPackageVersion[] = "%s";
}  // namespace chromeos
#endif  // USR_INCLUDE_XKEYBOARD_CONFIG_VERSION_H_
""" % version


if __name__ == '__main__':
  main()
