#!/bin/sh
# Copyright 2014 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This files wraps host gcc and disables two bogus warnings.

exec "$0.real" "$@" -Wno-maybe-uninitialized -Wno-unused-local-typedefs
