#!/bin/sh
# Copyright 2014 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This script wraps host gcc and disables a few bogus warnings.  It can
# be used to add compilation flags to all host compilations.  Flags
# are added at the beginning of the compilation command line so that
# the user can override them.
FLAGS_TO_ADD=(
  -Wno-maybe-uninitialized
  -Wno-unused-local-typedefs
  -Wno-deprecated-declarations
)

exec "$0".real ${FLAGS_TO_ADD[@]} "$@"
