#!/bin/bash
#
# Copyright (c) 2009 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# We use the tusbd USB-over-IP stack from www.incentivespro.com to do
# test configuration of some hardware.  Their userland is
# free-as-in-beer and we don't have redistribution rights, so we ask
# people who need it to download and install it on the target machine
# with this script.

set -e
set -u

TARGETDIR="$(dirname "$0")"

tmpdir=$(mktemp -d)

cd ${tmpdir}
wget http://incentivespro.com/usb-server.tar.gz

echo Verifying download...

# NB: sha256sum input must be hexhexhex<SPC><SPC>filename.  echo
# supplies one, we supply the other.
echo "31b022ce88e77f31f40ea4821d864e6099e70ee451937c978d6979e2ca6c84fe"\
     " usb-server.tar.gz" \
  |  sha256sum -c

echo Verified

# Don't want to delete temp directory until verification passes (so we can
# debug)
trap "rm -rf ${tmpdir}; exit 1" 1 2 13 15

tar -xzf usb-server.tar.gz

cd usb-server
sudo cp usbsrv ${TARGETDIR}/usbsrv.real
sudo cp usbsrvd ${TARGETDIR}
# Don't need usbsrvd-cl

cd /
echo USB server installation successful
rm -rf ${tmpdir}
