#!/bin/sh

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Wrapper for the USB-over-IP server control program from
# www.incentivespro.com that starts the server when necessary.

set -e

RUNFILE=/var/run/usbsrvd

SCRIPT_DIR="$(dirname "$0")"
EXE_DIR="${SCRIPT_DIR}"

# If installed in mod_for_test, this script lives in /usr/local/bin,
# but if installed with gmerge, it lives in /usr/bin.  Search
# ../local/bin if necessary.
if [ ! -f "${SCRIPT_DIR}/usbsrv.real" -a \
  -f "${SCRIPT_DIR}/../local/bin/usbsrv.real" ]; then
  EXE_DIR="${SCRIPT_DIR}/../local/bin"
fi

USBSRV_REAL="${EXE_DIR}/usbsrv.real"
USBSRVD="${EXE_DIR}/usbsrvd"

log() {
  echo "$@" | tee /dev/stderr | logger -t usbsrv-wrapper
}


if [ ! -f "${USBSRV_REAL}" ] ; then
  # We don't want to install this without explicit action
  log 'USB-over-IP script is not installed.  Run "install-usbsrv" to install'
  exit 1
fi


if [ ! -f ${RUNFILE} ] ; then
# For various reasons, we don't have an init script, so we start the
# server from this wrapper if needed
  log "Starting USB-over-IP server..."
  sudo modprobe tusbd
  sudo iptables -A INPUT -p tcp --dport 32032 -j ACCEPT
  sudo ${USBSRVD}
  sleep 1 # Allow server to stabilize since we don't have a good event to wait on
  sudo touch ${RUNFILE}
  log "USB-over-IP server started"
fi

exec sudo "${USBSRV_REAL}" "$@"
