# -*- python -*-

# Copyright (c) 2011 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import os

env = Environment()

# Keep ebuild up to date with appropriate headers, or else figure
# out how to get scons to handle header installation as well.
sources = env.Split("""
                    files/base/third_party/dmg_fp/dtoa.cc
                    files/base/third_party/dmg_fp/g_fmt.cc
                    files/base/third_party/icu/icu_utf.cc
                    files/base/third_party/nspr/prtime.cc
                    files/base/third_party/dynamic_annotations/dynamic_annotations.c
                    files/base/at_exit.cc
                    files/base/atomicops_internals_x86_gcc.cc
                    files/base/base_switches.cc
                    files/base/callback_internal.cc
                    files/base/command_line.cc
                    files/base/debug/debugger.cc
                    files/base/debug/debugger_posix.cc
                    files/base/debug/stack_trace.cc
                    files/base/debug/stack_trace_posix.cc
                    files/base/debug/trace_event.cc
                    files/base/environment.cc
                    files/base/file_path.cc
                    files/base/file_util.cc
                    files/base/file_util_posix.cc
                    files/base/metrics/histogram.cc
                    files/base/json/json_reader.cc
                    files/base/json/json_writer.cc
                    files/base/json/string_escape.cc
                    files/base/lazy_instance.cc
                    files/base/logging.cc
                    files/base/memory/ref_counted.cc
                    files/base/memory/scoped_temp_dir.cc
                    files/base/memory/weak_ptr.cc
                    files/base/message_loop.cc
                    files/base/message_loop_proxy.cc
                    files/base/message_loop_proxy_impl.cc
                    files/base/message_pump.cc
                    files/base/message_pump_default.cc
                    files/base/message_pump_glib.cc
                    files/base/message_pump_libevent.cc
                    files/base/native_library_linux.cc
                    files/base/pickle.cc
                    files/base/platform_file.cc
                    files/base/platform_file_posix.cc
                    files/base/rand_util.cc
                    files/base/rand_util_posix.cc
                    files/base/safe_strerror_posix.cc
                    files/base/string16.cc
                    files/base/stringprintf.cc
                    files/base/string_number_conversions.cc
                    files/base/string_piece.cc
                    files/base/string_split.cc
                    files/base/string_util.cc
                    files/base/synchronization/condition_variable_posix.cc
                    files/base/synchronization/lock.cc
                    files/base/synchronization/lock_impl_posix.cc
                    files/base/synchronization/waitable_event_posix.cc
                    files/base/sys_string_conversions_linux.cc
                    files/base/task.cc
                    files/base/threading/non_thread_safe_impl.cc
                    files/base/threading/platform_thread_posix.cc
                    files/base/threading/thread.cc
                    files/base/threading/thread_checker_impl.cc
                    files/base/threading/thread_collision_warner.cc
                    files/base/threading/thread_restrictions.cc
                    files/base/threading/thread_local_posix.cc
                    files/base/threading/thread_local_storage_posix.cc
                    files/base/time.cc
                    files/base/time_posix.cc
                    files/base/tracked.cc
                    files/base/tracked_objects.cc
                    files/base/utf_string_conversion_utils.cc
                    files/base/utf_string_conversions.cc
                    files/base/values.cc
                    files/base/vlog.cc
                    """)

env.Append(
    CPPPATH=['files'],
    CCFLAGS=['-g']
)
for key in Split('CC CXX AR RANLIB LD NM CFLAGS CCFLAGS'):
  value = os.environ.get(key)
  if value:
    env[key] = Split(value)

env['CCFLAGS'] += ['-fPIC',
                   '-fno-exceptions',
                   '-Wall',
                   '-Werror',
                   '-DOS_CHROMEOS',
                   '-DUSE_SYSTEM_LIBEVENT']

# Fix issue with scons not passing some vars through the environment.
for key in Split('PKG_CONFIG SYSROOT'):
  if os.environ.has_key(key):
    env['ENV'][key] = os.environ[key]

# glib, nss environment
env.ParseConfig('%s --cflags --libs glib-2.0 gtk+-2.0 nss'
                % env['ENV']['PKG_CONFIG'])

env.StaticLibrary('base', sources)
