#!/bin/sh
# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

XINPUT=/usr/bin/xinput

PROG=`basename $0`
COMMAND=$1

usage() {
  echo "Usage:"\
    "$PROG {status|log|taptoclick [on|off]|sensitivity [1-5]|"\
    "set <property> <value>}"
}

find_pad() {
  # Search for an xinput entry that contains the "pad" or "Pad"
  # Then, find a field that matches "id=".
  # Lastly, return the part of the field after the '='.
  return `xinput list | \
    awk '/[pP]ad/ { for (i=1; i<NF; i++) if ($i ~/id=/) print substr($i, 4) }'`
}

find_pad
DEVICE=$?
VALID=0

if [ $# = 0 ] ; then
  VALID=0
elif [ "$COMMAND" = "status" -a $# = 1 ] ; then
  $XINPUT list-props $DEVICE
  VALID=1
elif [ "$COMMAND" = "log" -a $# = 1 ] ; then
  $XINPUT set-prop $DEVICE "Logging Notify" 1
  VALID=1
elif [ "$COMMAND" = "taptoclick" -a $# = 2 ] ; then
  VALUE=$2
  case $VALUE in
  "on")
    $XINPUT set-prop $DEVICE "Tap Enable" 1
    VALID=1
    ;;
  "off")
    $XINPUT set-prop $DEVICE "Tap Enable" 0
    VALID=1
    ;;
  esac
elif [ "$COMMAND" = "sensitivity" -a $# = 2 ] ; then
  VALUE=$2
  $XINPUT set-prop $DEVICE "Sensitivity" "$VALUE"
  VALID=1
elif [ "$COMMAND" = "set" -a $# = 3 ] ; then
  PROP=$2
  VALUE=$3
  $XINPUT set-prop $DEVICE "$PROP" "$VALUE"
  VALID=1
fi

if [ $VALID = 0 ] ; then
  usage
fi
