# Copyright 2018 The Chromium OS Authors. All rights reserved.
# Distributed under the terms of the GNU General Public License v2

EAPI="5"

CROS_WORKON_COMMIT="c286e3a964cb7d198ca668e7df3e072640e86861"
CROS_WORKON_TREE=("49286d8b2b9af4d6c1632fbe46a8778220775f6c" "7b901b20e8abc5bb3dbf1f560f2c50b63f654fba")
CROS_WORKON_INCREMENTAL_BUILD=1
CROS_WORKON_LOCALNAME="platform2"
CROS_WORKON_PROJECT="chromiumos/platform2"
CROS_WORKON_OUTOFTREE_BUILD=1
CROS_WORKON_SUBTREE="common-mk cryptohome"

PLATFORM_SUBDIR="cryptohome"
PLATFORM_GYP_FILE="bootlockbox-client.gyp"

inherit cros-workon platform

DESCRIPTION="BootLockbox DBus client library for Chromium OS"
HOMEPAGE="https://chromium.googlesource.com/chromiumos/platform2/+/master/cryptohome/"

LICENSE="BSD-Google"
SLOT="0"
KEYWORDS="*"
IUSE="cros_host"

# D-Bus proxies generated by this client library depend on the code generator
# itself (chromeos-dbus-bindings) and produce header files that rely on
# libbrillo library.
DEPEND="
	cros_host? ( chromeos-base/chromeos-dbus-bindings )
	chromeos-base/libbrillo
"

RDEPEND="
	chromeos-base/cryptohome
"

src_install() {
	# Install DBus client library.
	platform_install_dbus_client_lib "bootlockbox"
}
