#!/bin/sh
# Copyright 2017 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This searches /etc/dptf for the most specific datavault available.
# E.g. SKU specific
#   /etc/dptf/dptf.santa.2.dv
# E.g. Model specific
#   /etc/dptf/dptf.santa.dv
# E.g. Default
#   /etc/dptf/dptf.dv

base_path='/etc/dptf/dptf.'
model="$(mosys platform model)"
sku="$(mosys platform sku)"
result=''

sku_suffix="${model}.${sku}"
model_suffix="${model}"


if [ -f "${base_path}${sku_suffix}.dv" ]; then
  result="${base_path}${sku_suffix}.dv"
elif [ -f "${base_path}${model_suffix}.dv" ]; then
  result="${base_path}${model_suffix}.dv"
fi

echo "${result}"
